"""Every relation test vector, against every check, one pytest node each.

A failure names the case and the check, so a run says which rule broke rather than
that something in the corpus did. The checks themselves are in `lib/gate.py`; what
they establish, and what they deliberately do not, is documented there.

    python3 -m pytest tests/relations
"""

import json
import os

import pytest

from tests.relations.lib import gate, paths

pytestmark = pytest.mark.skipif(
    not paths.bindings_available(),
    reason="protobuf bindings absent; run tests/relations/bootstrap.sh",
)

CASE_FILES = gate.case_files()
CHECK_NAMES = [c.__name__[len("check_") :] for c in gate.CHECKS]


def case_id(path):
    return os.path.relpath(os.path.splitext(path)[0], paths.cases_dir())


@pytest.fixture(scope="session")
def compiled():
    """Every case lowered once. Compiling is the slow part and every check reuses it."""
    ext = paths.extensions_dir()
    out = {}
    for path in CASE_FILES:
        try:
            out[case_id(path)] = gate.Case(path, ext)
        except Exception as e:
            out[case_id(path)] = e
    return out


@pytest.mark.parametrize("case_path", CASE_FILES, ids=case_id)
def test_compiles(case_path, compiled):
    """The case file loads strictly and lowers to a plan."""
    got = compiled[case_id(case_path)]
    if isinstance(got, Exception):
        pytest.fail(f"{type(got).__name__}: {got}")


@pytest.mark.parametrize("check", gate.CHECKS, ids=CHECK_NAMES)
@pytest.mark.parametrize("case_path", CASE_FILES, ids=case_id)
def test_check(case_path, check, compiled):
    case = compiled[case_id(case_path)]
    if isinstance(case, Exception):
        pytest.skip("the case does not compile; test_compiles reports that")
    result = check(case)
    if result is gate.SKIP:
        pytest.skip(f"{check.__name__} does not apply to a {case.kind} case")
    assert result is None, result


def test_ids_are_unique(compiled):
    """Two cases with one id would make a consumer's report ambiguous."""
    seen = {}
    for name, case in compiled.items():
        if isinstance(case, Exception):
            continue
        seen.setdefault(case.doc["id"], []).append(name)
    duplicated = {k: v for k, v in seen.items() if len(v) > 1}
    assert not duplicated, duplicated


def test_coverage_ratchet(compiled):
    """What the corpus covers may grow and may not shrink.

    The baseline is regenerated by `build.py --write`, so widening coverage is a
    deliberate diff on a committed file rather than a number nobody looks at.
    """
    counts = gate.Counter()
    for case in compiled.values():
        if not isinstance(case, Exception):
            gate.coverage(case.plan, counts)
    baseline = paths.baseline_path()
    assert os.path.exists(baseline), "run build.py --write to record a baseline"
    previous = json.load(open(baseline))
    dropped = {
        k: (v, counts.get(k, 0)) for k, v in previous.items() if counts.get(k, 0) < v
    }
    assert not dropped, f"coverage dropped (baseline, now): {dropped}"
